import {
	Material,
	MaterialLiquid,
	MaterialLogic,
	MaterialPortal,
	MaterialTransparent,
	MaterialTransparent$1,
} from "./material.js";

export default {
	air: new MaterialTransparent(),
	grass: new Material(),
	ground: new Material(),
	wood: new Material(),
	rock: new Material(),
	iron: new Material(),
	anvil: new Material(),
	water: new MaterialLiquid(),
	lava: new MaterialLiquid(),
	leaves: new Material(),
	plants: new MaterialTransparent(),
	vine: new MaterialTransparent(),
	sponge: new Material(),
	cloth: new Material(),
	fire: new MaterialTransparent(),
	sand: new Material(),
	carpet: new MaterialTransparent$1(),
	glass: new MaterialTransparent$1(),
	redstoneLight: new Material(),
	tnt: new Material(),
	coral: new Material(),
	ice: new MaterialTransparent$1(),
	packedIce: new Material(),
	snow: new MaterialTransparent$1(),
	craftedSnow: new Material(),
	cactus: new MaterialTransparent$1(),
	clay: new Material(),
	gourd: new Material(),
	dragonEgg: new Material(),
	portal: new MaterialPortal(),
	cake: new MaterialTransparent$1(),
	pressure_plate: new MaterialTransparent$1(),
	web: new MaterialTransparent(),
	slime: new MaterialTransparent$1(),
	slab: new MaterialTransparent$1(),
	barrier: new Material(),
	circuits: new MaterialLogic().setTranslucent(),
	solidTransparent: new MaterialTransparent$1(),
	transparent: new MaterialTransparent(),
};
